// Generate docs/INVENTORY.md — every countable fact about the library.
//
// Run: node tools/inventory.mjs          (writes the file)
//      node tools/inventory.mjs --check  (fails if it is out of date)
//
// Inventory drifts when it is written by hand into prose, because prose is
// updated when someone remembers to. So no other document states a count,
// a device total or a circuit list: they link here, and this is generated
// from the catalogue and the circuits themselves.
//
// The --check mode runs in the test suite, so a stale inventory is a test
// failure rather than something a reader discovers later.

import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { CIRCUITS, GROUP_ORDER, buildCircuit } from '../web/js/circuits.js';

const root = new URL('..', import.meta.url);
const out = new URL('docs/INVENTORY.md', root);

function counts(id) {
  const c = buildCircuit(id);
  const n = c.counts();
  return {
    relays: n.relays,
    transistors: n.transistors,
    diodes: n.diodes,
    resistors: n.resistors,
    nets: c.netCount,
    // devices you would have to physically build, so contacts count
    total: n.relays + n.transistors + n.diodes + n.resistors,
  };
}

// Group the catalogue the way the picker does: technology, then subsection.
const sections = new Map();
for (const g of GROUP_ORDER) {
  const [tech, sub] = g.split(' · ');
  if (!CIRCUITS.some(e => e.group === g)) continue;
  if (!sections.has(tech)) sections.set(tech, []);
  sections.get(tech).push({ sub, entries: CIRCUITS.filter(e => e.group === g) });
}

const rows = [];
for (const [tech, subs] of sections) {
  for (const { sub, entries } of subs) {
    for (const e of entries) rows.push({ tech, sub, ...e, ...counts(e.id) });
  }
}

// Which concepts exist in which technology — the matrix is the point of
// the library, so a hole in it is worth seeing at a glance.
const CONCEPT = {
  'Inverter / NOT': ['not', 'cmosinv', 'nmosinv'],
  'AND': ['and', 'cmosand', 'nmosand'],
  'OR': ['or', 'cmosor', 'nmosor'],
  'XOR': ['xor', 'cmosxor', 'nmosxor'],
  'NAND': ['nand', 'cmosnand', 'nmosnand'],
  'NOR': ['nor', 'cmosnor', 'nmosnor'],
  'Ring oscillator': ['osc', 'cmosring', 'nmosring'],
  'Decoder': ['dec24', 'cmosdec', 'nmosdec'],
  'D latch': ['dlatch', 'cmoslatch', 'nmoslatch'],
  'Adder': ['add4', 'cmosfa', 'nmosadd4'],
  'Register file': [null, 'regfile', null],
  'ALU': [null, 'alu4', 'nmosalu'],
  'ROM': [null, 'romcmos', 'rom8'],
  'Tri-state bus': [null, 'tristate', null],
};

const byId = new Map(CIRCUITS.map(e => [e.id, e]));
const pad = (s, n) => String(s).padEnd(n);
const num = (s, n) => String(s).padStart(n);

let md = `<!-- GENERATED by tools/inventory.mjs — do not edit by hand. -->
<!-- Run \`node tools/inventory.mjs\` to refresh; the test suite checks it. -->

# Inventory

Every countable fact about the library, generated from the catalogue and
from building each circuit. No other document repeats these numbers — they
link here instead, because inventory written into prose goes stale quietly.

**${CIRCUITS.length} circuits** across ${sections.size} sections.

`;

// ── the technology matrix ────────────────────────────────────────────────
md += `## The matrix

The library exists to build the same logic several ways and compare, so
this is the table that matters. A dash is either work not done or a thing
that technology genuinely cannot do — the notes below say which.

| Concept | Relays | CMOS | NMOS |
|---|---|---|---|
`;
for (const [concept, ids] of Object.entries(CONCEPT)) {
  const cell = id => (id && byId.has(id) ? byId.get(id).name : '—');
  md += `| ${pad(concept, 16)} | ${pad(cell(ids[0]), 24)} | ${pad(cell(ids[1]), 20)} | ${cell(ids[2])} |\n`;
}
md += `
Two dashes are results rather than gaps, and worth stating so nobody
"fixes" them: **tri-state needs a complementary pair**, so it cannot exist
in relays or in NMOS-with-resistor-loads; and the **NMOS ALU** is stuck
with a mux tree for exactly that reason, which is what the Tri-State Bus
circuit exists to explain.

`;

// ── per-section listings ─────────────────────────────────────────────────
md += `## Circuits\n`;
for (const [tech, subs] of sections) {
  const all = subs.flatMap(s => s.entries);
  md += `\n### ${tech} (${all.length})\n\n`;
  md += `| Circuit | Group | Relays | Transistors | Diodes | Resistors | Nets |\n`;
  md += `|---|---|--:|--:|--:|--:|--:|\n`;
  for (const { sub, entries } of subs) {
    for (const e of entries) {
      const c = counts(e.id);
      const dash = v => (v === 0 ? '·' : v);
      md += `| ${e.name} | ${sub || '—'} | ${dash(c.relays)} | ${dash(c.transistors)} | ${dash(c.diodes)} | ${dash(c.resistors)} | ${c.nets} |\n`;
    }
  }
}

// ── totals ───────────────────────────────────────────────────────────────
const sum = k => rows.reduce((n, r) => n + r[k], 0);
const biggest = [...rows].sort((a, b) => b.total - a.total).slice(0, 5);
md += `
## Totals

| | Count |
|---|--:|
| Circuits | ${CIRCUITS.length} |
| Groups | ${GROUP_ORDER.filter(g => CIRCUITS.some(e => e.group === g)).length} |
| Relays | ${sum('relays')} |
| Transistors | ${sum('transistors')} |
| Diodes | ${sum('diodes')} |
| Resistors | ${sum('resistors')} |

### Largest circuits

| Circuit | Devices | Nets |
|---|--:|--:|
`;
for (const r of biggest) md += `| ${r.name} | ${r.total} | ${r.nets} |\n`;

// ── test suite ───────────────────────────────────────────────────────────
// Only run the suite when *writing*. The suite calls this script with
// --check, so running it from there too would recurse forever.
let suite = '(run `node test/sim-test.mjs`)';
if (!process.argv.includes('--check')) {
  try {
    // The suite prints one line per failure and nothing per pass, so the
    // happy path is tiny — but a broken run can print thousands of lines,
    // and the default 1 MB pipe buffer kills the child with SIGTERM when
    // it overflows. That looks exactly like "the generator crashed" and
    // sent one debugging session down the wrong path; 64 MB is plenty.
    const res = execFileSync('node', ['test/sim-test.mjs'],
      { cwd: new URL('.', root).pathname, encoding: 'utf8',
        maxBuffer: 64 * 1024 * 1024 });
    suite = res.trim().split('\n').pop();
  } catch {
    suite = '(suite failed — fix that before trusting this file)';
  }
}
md += `
## Test suite

\`node test/sim-test.mjs\` → **${suite}**

Every circuit is built and checked for sane geometry and buses; most have a
full truth-table sweep. Device circuits assert on drive *strength* as well
as value, because a lit lamp is not a driven net.
`;

// ── write or check ───────────────────────────────────────────────────────
const wanted = md;
if (process.argv.includes('--check')) {
  let have = '';
  try { have = readFileSync(out, 'utf8'); } catch { /* missing */ }
  // The suite line embeds this run's own check count, which changes as
  // tests are added — compare everything above it, which is what actually
  // describes the library.
  const trim = s => s.split('## Test suite')[0];
  if (trim(have) !== trim(wanted)) {
    console.error('docs/INVENTORY.md is out of date — run: node tools/inventory.mjs');
    process.exit(1);
  }
  console.log('inventory up to date');
} else {
  writeFileSync(out, wanted);
  console.log(`wrote docs/INVENTORY.md — ${CIRCUITS.length} circuits`);
}
